# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_log(object):
    def setupUi(self, Dialog_log):
        Dialog_log.setObjectName("Dialog_log")
        Dialog_log.resize(667, 415)
        self.pushButton = QtWidgets.QPushButton(Dialog_log)
        self.pushButton.setGeometry(QtCore.QRect(130, 310, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color:white")
        self.pushButton.setObjectName("pushButton")
        self.label_content = QtWidgets.QLabel(Dialog_log)
        self.label_content.setGeometry(QtCore.QRect(20, 80, 621, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_content.setFont(font)
        self.label_content.setText("")
        self.label_content.setAlignment(QtCore.Qt.AlignCenter)
        self.label_content.setObjectName("label_content")
        self.label_type = QtWidgets.QLabel(Dialog_log)
        self.label_type.setGeometry(QtCore.QRect(280, 10, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_type.setFont(font)
        self.label_type.setText("")
        self.label_type.setObjectName("label_type")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog_log)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 310, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color:white")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_up = QtWidgets.QLabel(Dialog_log)
        self.label_up.setGeometry(QtCore.QRect(220, 10, 51, 41))
        self.label_up.setStyleSheet("border-image:none;\n"
"border:none;")
        self.label_up.setText("")
        self.label_up.setObjectName("label_up")

        self.retranslateUi(Dialog_log)
        QtCore.QMetaObject.connectSlotsByName(Dialog_log)

    def retranslateUi(self, Dialog_log):
        _translate = QtCore.QCoreApplication.translate
        Dialog_log.setWindowTitle(_translate("Dialog_log", "Dialog"))
        self.pushButton.setText(_translate("Dialog_log", "取消"))
        self.pushButton_2.setText(_translate("Dialog_log", "确认"))
        self.pushButton.setStyleSheet("color: Black")
        self.pushButton_2.setStyleSheet("color: Black")
