# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logwindow_duandu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_log(object):
    def setupUi(self, Dialog_log):
        Dialog_log.setObjectName("Dialog_log")
        Dialog_log.resize(775, 631)
        Dialog_log.setStyleSheet("")
        self.label_up = QtWidgets.QLabel(Dialog_log)
        self.label_up.setGeometry(QtCore.QRect(180, 70, 51, 51))
        self.label_up.setStyleSheet("border-image:none;\n"
"border:none;")
        self.label_up.setText("")
        self.label_up.setObjectName("label_up")
        self.label_type = QtWidgets.QLabel(Dialog_log)
        self.label_type.setGeometry(QtCore.QRect(250, 70, 281, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_type.setFont(font)
        self.label_type.setObjectName("label_type")
        self.label_content = QtWidgets.QLabel(Dialog_log)
        self.label_content.setGeometry(QtCore.QRect(80, 170, 621, 191))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_content.setFont(font)
        self.label_content.setAlignment(QtCore.Qt.AlignCenter)
        self.label_content.setObjectName("label_content")
        self.pushButton_ok = QtWidgets.QPushButton(Dialog_log)
        self.pushButton_ok.setGeometry(QtCore.QRect(180, 520, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ok.setFont(font)
        self.pushButton_ok.setStyleSheet("")
        self.pushButton_ok.setText("")
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_no = QtWidgets.QPushButton(Dialog_log)
        self.pushButton_no.setGeometry(QtCore.QRect(470, 520, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_no.setFont(font)
        self.pushButton_no.setStyleSheet("color:gray")
        self.pushButton_no.setText("")
        self.pushButton_no.setObjectName("pushButton_no")
        self.pushButton_Return = QtWidgets.QPushButton(Dialog_log)
        self.pushButton_Return.setGeometry(QtCore.QRect(490, 410, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Return.setFont(font)
        self.pushButton_Return.setStyleSheet("QPushButton{background-color: rgb(58, 58, 58);\n"
"color: rgb(221, 221, 221);\n"
"border-radius:10px}\n"
":pressed{background-color: rgb(118, 118, 118);\n"
"padding-top:5px;\n"
"    padding-left:5px;\n"
"color: rgb(50, 50, 50);\n"
"border-radius:10px}\n"
"")
        self.pushButton_Return.setObjectName("pushButton_Return")
        self.pushButton_Load = QtWidgets.QPushButton(Dialog_log)
        self.pushButton_Load.setGeometry(QtCore.QRect(640, 410, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Load.setFont(font)
        self.pushButton_Load.setStyleSheet("QPushButton{background-color: rgb(58, 58, 58);\n"
"color: rgb(221, 221, 221);\n"
"border-radius:10px}\n"
":pressed{background-color: rgb(118, 118, 118);\n"
"padding-top:5px;\n"
"    padding-left:5px;\n"
"color: rgb(50, 50, 50);\n"
"border-radius:10px}\n"
"")
        self.pushButton_Load.setObjectName("pushButton_Load")
        self.pushButton_heatup = QtWidgets.QPushButton(Dialog_log)
        self.pushButton_heatup.setGeometry(QtCore.QRect(340, 410, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_heatup.setFont(font)
        self.pushButton_heatup.setStyleSheet("QPushButton{background-color: rgb(58, 58, 58);\n"
"color: rgb(221, 221, 221);\n"
"border-radius:10px}\n"
":pressed{background-color: rgb(118, 118, 118);\n"
"padding-top:5px;\n"
"    padding-left:5px;\n"
"color: rgb(50, 50, 50);\n"
"border-radius:10px}\n"
"")
        self.pushButton_heatup.setObjectName("pushButton_heatup")
        self.lineEdit = QtWidgets.QLineEdit(Dialog_log)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 775, 631))
        self.lineEdit.setStyleSheet("border-radius: 30px;\n"
"background-color: qlineargradient(spread:pad, x1:0.01, y1:0.01, x2:0, y2:0.01, stop:0 rgba(198, 198, 198, 255), stop:1 rgba(0, 0, 0, 255));\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.label_type_2 = QtWidgets.QLabel(Dialog_log)
        self.label_type_2.setGeometry(QtCore.QRect(150, 60, 411, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_type_2.setFont(font)
        self.label_type_2.setStyleSheet("background-color: rgb(99, 99, 99);\n"
"border-radius:30px")
        self.label_type_2.setText("")
        self.label_type_2.setObjectName("label_type_2")
        self.label_content_2 = QtWidgets.QLabel(Dialog_log)
        self.label_content_2.setGeometry(QtCore.QRect(60, 160, 650, 230))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_content_2.setFont(font)
        self.label_content_2.setStyleSheet("background-color: rgb(99, 99, 99);\n"
"border-radius:30px")
        self.label_content_2.setText("")
        self.label_content_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_content_2.setObjectName("label_content_2")
        self.pushButton_down = QtWidgets.QPushButton(Dialog_log)
        self.pushButton_down.setGeometry(QtCore.QRect(190, 410, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_down.setFont(font)
        self.pushButton_down.setStyleSheet("QPushButton{background-color: rgb(58, 58, 58);\n"
"color: rgb(221, 221, 221);\n"
"border-radius:10px}\n"
":pressed{background-color: rgb(118, 118, 118);\n"
"padding-top:5px;\n"
"    padding-left:5px;\n"
"color: rgb(50, 50, 50);\n"
"border-radius:10px}\n"
"")
        self.pushButton_down.setObjectName("pushButton_down")
        self.open_un = QtWidgets.QPushButton(Dialog_log)
        self.open_un.setGeometry(QtCore.QRect(40, 410, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.open_un.setFont(font)
        self.open_un.setStyleSheet("QPushButton{background-color: rgb(58, 58, 58);\n"
"color: rgb(221, 221, 221);\n"
"border-radius:10px}\n"
":pressed{background-color: rgb(118, 118, 118);\n"
"padding-top:5px;\n"
"    padding-left:5px;\n"
"color: rgb(50, 50, 50);\n"
"border-radius:10px}\n"
"")
        self.open_un.setText("")
        self.open_un.setObjectName("open_un")
        self.lineEdit.raise_()
        self.label_content_2.raise_()
        self.label_type_2.raise_()
        self.label_up.raise_()
        self.label_type.raise_()
        self.label_content.raise_()
        self.pushButton_ok.raise_()
        self.pushButton_no.raise_()
        self.pushButton_Return.raise_()
        self.pushButton_Load.raise_()
        self.pushButton_heatup.raise_()
        self.pushButton_down.raise_()
        self.open_un.raise_()

        self.retranslateUi(Dialog_log)
        QtCore.QMetaObject.connectSlotsByName(Dialog_log)

    def retranslateUi(self, Dialog_log):
        _translate = QtCore.QCoreApplication.translate
        Dialog_log.setWindowTitle(_translate("Dialog_log", "Dialog"))
        self.label_type.setText(_translate("Dialog_log", "123456789876543567897654567876543567"))
        self.label_content.setText(_translate("Dialog_log", "1233455TVYTYR5B"))
        self.pushButton_Return.setText(_translate("Dialog_log", "退料"))
        self.pushButton_Load.setText(_translate("Dialog_log", "上料"))
        self.pushButton_heatup.setText(_translate("Dialog_log", "升温"))
        self.pushButton_down.setText(_translate("Dialog_log", "下降"))
