# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openfile.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_file(object):
    def setupUi(self, Dialog_file):
        Dialog_file.setObjectName("Dialog_file")
        Dialog_file.resize(825, 552)
        self.listView_file = QtWidgets.QListView(Dialog_file)
        self.listView_file.setGeometry(QtCore.QRect(50, 90, 721, 371))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.listView_file.setFont(font)
        self.listView_file.setStyleSheet("font: 17pt \"Arial\";\n"
"color: rgb(255, 255, 255，0);")
        self.listView_file.setObjectName("listView_file")
        self.pushButton = QtWidgets.QPushButton(Dialog_file)
        self.pushButton.setGeometry(QtCore.QRect(70, 480, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog_file)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 480, 141, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Dialog_file)
        self.label.setGeometry(QtCore.QRect(330, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog_file)
        QtCore.QMetaObject.connectSlotsByName(Dialog_file)

    def retranslateUi(self, Dialog_file):
        _translate = QtCore.QCoreApplication.translate
        Dialog_file.setWindowTitle(_translate("Dialog_file", "Dialog"))
        self.pushButton.setText(_translate("Dialog_file", "取消"))
        self.pushButton_2.setText(_translate("Dialog_file", "确认"))
        self.label.setText(_translate("Dialog_file", "选择GCODE"))
